# Run Docker Image (Execute in the parent directory)
# xhost +local:docker
# docker-compose --verbose --env-file docker_scripts/compose-file.env -f envs/pha-22/docker-compose.yaml up -d
version: '3'

services:
  pha-cont:
    image: ${DOC_IMG}:${DOC_TAG}
    container_name: ${CONT_NAME}
    env_file:
      - compose-file.env
    network_mode: host
    runtime: nvidia
    privileged: true
    environment:
      - DISPLAY=${DISPLAY_VAR}
      - NVIDIA_VISIBLE_DEVICES=${GPU_DEVICES}
      - NVIDIA_DRIVER_CAPABILITIES=all
      - QT_X11_NO_MITSHM=1
    shm_size: ${SHM_SIZE}
    deploy:
      resources:
        limits:
          cpus: ${CPU_LIM}
          memory: ${CPU_MEM_LIM}
        reservations:
          cpus: ${CPU_RES}
          memory: ${CPU_MEM_RES}
          devices:
            - driver: nvidia
              device_ids: ${GPU_IDS}
              capabilities: [gpu]
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ${SSI_PATH}:/home/pha/docker_share
      - /media/${USERNAME}:/media/pha
      - /dev:/dev
    tty: true
    stdin_open: true
    #entrypoint: [ "/bin/bash", "-c" ]
