# Run Docker Image (Execute in the parent directory)
# xhost +local:docker
# docker-compose -f envs/pha-22/docker-compose.yaml up -d
version: '3'

services:
  pha-dynamic:
    image: ${DOC_IMG}:${DOC_TAG}
    container_name: ${CONT_NAME}
    env_file:
      - compose-file.env
    network_mode: host
    privileged: true
    environment:
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1
    shm_size: 16gb
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /home/${USER}/schreibtisch/pha_docker_files/docker_share:/home/pha/docker_share
      - /media/${USER}:/media/pha
      - /dev:/dev
    tty: true
    stdin_open: true
    #entrypoint: [ "/bin/bash", "-c" ]
