# Run Docker Image (Execute in the parent directory)
# xhost +local:docker
# docker-compose --verbose --env-file docker_scripts/compose-file.env -f docker_scripts/docker-compose.yaml up -d
version: '3'

services:
  pha-user:
    image: ${CUSTOM_NAME}:${CUSTOM_TAG}
    build: 
      context: ../.
      dockerfile: ${DOCKERFILE_PATH}
      no_cache: true
      args:
        - IMAGE_NAME=${DOC_IMG}
        - IMAGE_VERSION=${DOC_TAG}
        - UID=${UID}
        - GID=${GID}
        - USERNAME=${USERNAME}
    container_name: ${CONT_NAME}
    env_file:
      - compose-file.env
    network_mode: host
    runtime: nvidia
    privileged: true
    environment:
      - DISPLAY=$DISPLAY
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - QT_X11_NO_MITSHM=1
    shm_size: 16gb
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /home/${USER}/schreibtisch/pha_docker_files/docker_share:/home/${USER}/docker_share
      - /media/${USER}:/media/${USER}
      - /dev:/dev
    tty: true
    stdin_open: true
    #entrypoint: [ "/bin/bash", "-c" ]
